In [ ]:
import math
import os 
import numpy as np
from scipy.optimize import linprog
import pandas as pd
from pulp import LpMaximize, LpMinimize, LpProblem, LpStatus, lpSum, LpVariable
import cvxpy as cp

In [ ]:
#import baseline optimization results
optimization_results = pd.read_csv("../outputs/baseline_results.csv").drop(columns="Unnamed: 0")
optimization_results

,v0,v1,v2,v3,v4,v5,v6,v7,v8,v9,...,v160,v161,v162,v163,egypt_irr,egypt_90,egypt_low_had,sudan_irr,sudan_90,ethiopia_hydro
0,0.000513,0.114183,0.379610,0.222861,-0.912948,0.452649,0.260217,0.235133,-0.412399,0.729811,...,0.361710,0.359652,0.515373,0.375135,5.583528,1.079809,0.541667,0.027608,0.0,14.418962
1,0.005551,0.114852,0.416813,0.215447,-0.673022,0.456056,-0.329024,0.234759,-0.018857,0.743872,...,0.359905,0.096117,0.525507,0.365050,4.889959,1.355717,0.245833,0.000000,0.0,14.473707
2,0.005551,0.114852,0.416813,0.215447,-0.673022,0.456056,-0.318718,0.234759,-0.018857,0.743872,...,0.359905,0.096117,0.706763,0.365144,4.668365,1.237320,0.295833,0.000000,0.0,14.373276
3,0.005551,0.088394,0.579024,0.310944,0.901105,0.007324,-0.289949,0.234686,0.478925,0.421958,...,0.361385,0.315424,0.521779,0.395253,8.227111,2.286887,0.012500,0.067783,0.0,15.000933
4,0.022721,0.114852,0.416813,0.206873,-0.673022,0.456056,-0.318718,0.234759,-0.036241,0.744584,...,0.386367,0.096117,0.706763,0.365144,5.078874,0.863157,0.570833,0.008685,0.0,13.695218
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552,0.326885,0.106877,0.545884,0.336976,-0.668031,0.437772,-0.419885,0.869253,0.461072,0.744024,...,0.376803,0.188286,0.282503,0.385069,4.992584,0.440134,0.558333,0.087050,0.0,11.162882
553,0.000151,0.028225,0.393737,0.309436,-0.742859,0.191598,-0.376609,0.230249,-0.751094,0.744065,...,0.096033,0.027555,0.114251,0.397327,4.692767,1.185513,0.633333,0.395626,0.0,15.055595
554,0.003841,0.024536,0.447966,0.306452,-0.846223,0.457366,-0.377002,0.209600,0.481661,0.699339,...,0.365742,0.065873,0.279207,0.346387,4.654900,1.393756,0.470833,0.275966,0.0,15.042024
555,0.001132,0.022049,0.478721,0.308261,-0.747247,0.411032,-0.360748,0.344056,-0.199549,0.360655,...,0.397008,0.144051,0.298246,0.425433,7.540867,1.966258,0.016667,0.362593,0.0,15.062063
556,0.000151,0.028225,0.393737,0.309436,-0.742859,0.191598,-0.376609,0.233875,-0.751094,0.744065,...,0.096033,0.068354,0.114251,0.397327,4.705627,1.173453,0.637500,0.391764,0.0,15.055337

In [ ]:
#separate out the policy variables with the objective values
policies, objectives = optimization_results.iloc[:, :-6], optimization_results.iloc[:, -6:]

NameError: name 'optimization_results' is not defined

In [ ]:
#import csv file with characteristic function values
current_dir = os.getcwd()
file_path = os.path.join(current_dir,"char_functions.xlsx") #insert file here
char_function = pd.read_excel(file_path)

In [ ]:
char_function = char_function.where(pd.notnull(char_function), 'Null')
unique_coalitions_char_values = char_function.characteristic_functions.tolist()

In [ ]:
char_function = char_function.iloc[1:]
char_function

             Coalitions  characteristic_functions
1                 Egypt                5422599200
2                 Sudan                 460925711
3              Ethiopia                 463206226
4           Egypt Sudan                6716005000
5        Egypt Ethiopia                6595746000
6        Sudan Ethiopia                 925918900
7  Egypt Sudan Ethiopia                7053858000